# Generated by Django 5.1.6 on 2025-03-09 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, null=True)),
                ('infraStructure_or_Constructions', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.FileField(upload_to='documents/')),
                ('documents_metaData', models.CharField(max_length=50)),
                ('document_discpline_or_trade', models.CharField(max_length=15)),
                ('document_description', models.TextField(null=True)),
                ('issue_date', models.DateField()),
                ('recived_date', models.DateField()),
                ('submition', models.CharField(max_length=20)),
                ('issuer', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.projects')),
            ],
        ),
    ]
