# Generated by Django 5.1.6 on 2025-03-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='document_type',
            new_name='document_extension',
        ),
        migrations.AddField(
            model_name='documents',
            name='documents_type',
            field=models.CharField(choices=[('DWD', 'Drawings'), ('RFI', 'Request for Information'), ('SUB', 'Submittals'), ('EIR', 'External Inspection Request')], default='UNKNOWN', max_length=20, verbose_name='d_type'),
        ),
        migrations.AddField(
            model_name='documents',
            name='revision',
            field=models.CharField(default='rev00', max_length=20),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_code',
            field=models.CharField(default='UNKNOWN', max_length=10, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='document_discpline_or_trade',
            field=models.CharField(choices=[('ARCH', 'Architectural'), ('CI', 'Civil'), ('ME', 'Mechanical'), ('ELE', 'Electrical')], max_length=15, verbose_name='discipline'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='submition',
            field=models.CharField(choices=[('A', 'Approved'), ('B', 'Approved with Comments'), ('C', 'Revice and resumit'), ('D', 'Rejected')], max_length=20, verbose_name='action'),
        ),
    ]
