# Generated by Django 5.1.6 on 2025-04-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_projectname_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectname',
            name='dueDate',
            field=models.DateField(),
        ),
    ]
