# Generated by Django 5.1.6 on 2025-04-04 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_projectname_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.projectname'),
        ),
    ]
